export interface Player {
    id: string,
    name: string,
    number: number,
    idTeams: string[],
    photoUrl?: string,
    birthday?: string,
    address?: string,
    position?: string,
    idFavorite?: string,
    mail?: string,
    contact?: string,
    social?: string,
    likes?: number,
}